// <auto-generated />
using System;
using LayoutValidator.Api.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LayoutValidator.Api.Dados.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260820034633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LayoutValidator.Api.Modelos.CampoCadastrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LayoutId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("CampoCadastrado");
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.LayoutCadastrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Delimitador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.RegraCampoCadastrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveRegra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametrosJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampoId");

                    b.ToTable("RegraCampoCadastrada");
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.CampoCadastrado", b =>
                {
                    b.HasOne("LayoutValidator.Api.Modelos.LayoutCadastrado", null)
                        .WithMany("Campos")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.RegraCampoCadastrada", b =>
                {
                    b.HasOne("LayoutValidator.Api.Modelos.CampoCadastrado", null)
                        .WithMany("Regras")
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.CampoCadastrado", b =>
                {
                    b.Navigation("Regras");
                });

            modelBuilder.Entity("LayoutValidator.Api.Modelos.LayoutCadastrado", b =>
                {
                    b.Navigation("Campos");
                });
#pragma warning restore 612, 618
        }
    }
}
